steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build --build-arg MODEL=$_MODEL --build-arg MODELFILE="$_MODELFILE" -t $_REPO_OWNER/$_IMAGE_NAME:$_IMAGE_TAG .']
  env:
    - "DOCKER_BUILDKIT=1"
  secretEnv: ['USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $_REPO_OWNER/$_IMAGE_NAME:$_IMAGE_TAG']
  secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
  - versionName: projects/$_PROJECT_ID/secrets/$_DOCKER_PASSWORD_SECRET_NAME/versions/$_DOCKER_PASSWORD_SECRET_VERSION
    env: 'PASSWORD'
  - versionName: projects/$_PROJECT_ID/secrets/$_DOCKER_USERNAME_SECRET_NAME/versions/$_DOCKER_USERNAME_SECRET_VERSION
    env: 'USERNAME'
# options:
#   machineType: 'E2_HIGHCPU_32'